<template>
  <v-container>
    <v-row>
      <v-spacer></v-spacer>
      <v-card-title>Automatic - Controls</v-card-title>
      <v-spacer></v-spacer>
    </v-row>
    <v-row>
      <v-col sm="6">
        <v-combobox
          clearable
          label="select Recipe"
          :items="dropdownItems"
          v-model="selectedRecipeName"
        ></v-combobox>
      </v-col>
      <v-col sm="4">
        <v-btn-toggle v-model="automaticControls.brewmode" shaped mandatory>
          <v-btn value="brew" prepend-icon="mdi-barley" stacked> Brew </v-btn>
          <v-btn value="boil" prepend-icon="mdi-hops" stacked> Boil </v-btn>
        </v-btn-toggle>
      </v-col>
      <v-col sm="2">
        <v-switch
          color="success"
          append-icon="mdi-refresh-auto"
          inset
          @input="switchClick()"
          v-model="automaticControls.autoMode"
        ></v-switch>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
const serverUrl = "http://localhost:5000";
import axios from "axios";

export default {
  props: {
    modelValue: Object,
  },
  data() {
    return {
      dropdownObjects: [], // gets filles by fetchDropdownEntries-Objects!
      dropdownItems: [], //gets filled by fetchDropdownEntries-names!

      //Ids are generated by a computed functionn name comes directly from dropdown
      selectedRecipeName: null,
      
    };
  },
  computed: {
    automaticControls: {
      get() {
        return this.modelValue;
      },
      set(value){
        this.$emit('update: modelValue', value);
      }
    },
  },
  methods: {
    switchClick() {
      this.$emit("switch-click");
    },

    //get items / objects for the recipe-selection
    async fetchSelectEntries() {
      // Axios GET-Request (dropdown!)
      try {
        const response = await axios.get(`${serverUrl}/recipepanelAPI/`);
        this.dropdownObjects = response.data;
        this.dropdownItems = this.dropdownObjects.map((item) => item.name);
      } catch (error) {
        console.error("Error fetchSelectEntries: ", error);
      }
    },
  },
  

    // _________________________________________________________________________________________ watch
    watch: {
    selectedRecipeName: function (newVal) {
      if (newVal) {
        // Find the corresponding ID for the selected name
        const selectedObject = this.dropdownObjects.find(
          (obj) => obj.name === newVal
        );
        this.automaticControls.selectedID = selectedObject.id;
      } else {
        // If no item is selected, reset the selectedItemId
        this.automaticControls.selectedID = null;
      }
    },
  },
  

  mounted() {
    this.fetchSelectEntries();
  },
};
</script>
